version: "3.8"

volumes:
  db-data:

services:
  api-nginx:
    container_name: api-nginx
    build:
      context: .
      dockerfile: ./dockerfiles/nginx.dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api-php
      - api-mysql
  api-php:
    container_name: api-php
    build:
      context: .
      dockerfile: ./dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html

  api-mysql:
    container_name: api-mysql
    image: mysql:8.2.0
    ports:
      - "4306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
  api-composer:
    container_name: api-composer
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  api-artisan:
    container_name: api-artisan
    build:
      context: .
      dockerfile: ./dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
