version: "3.8"

services:
  nginx:
    container_name: nginx-api
    image: teachertribe-elearn-api-nginx
    build:
      context: .
      dockerfile: ./dockerfiles/nginx.dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
      - mysql
  php:
    container_name: php
    image: teachertribe-elearn-api-php
    build:
      context: .
      dockerfile: ./dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
      - /var/www/html/vendor

  mysql:
    container_name: mysql
    image: mysql:8.2.0
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
