version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine3.17
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  php:
    container_name: php
    build: 
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
  mysql:
    container_name: mysql
    image: mysql:8.2.0
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=teachertribe-elearn-api
    ports:
      - "4306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
 