# fly.toml app configuration file generated for teachertribe-elearn-api on 2023-11-18T15:27:44+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "teachertribe-elearn-api"
primary_region = "sin"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.2"

[env]
  APP_ENV = "production"
  DB_CONNECTION = "mysql"
  DB_DATABASE = "teachertribe-elearn-api"
  DB_HOST = "aws.connect.psdb.cloud"
  DB_PORT = "3306"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  MAIL_ENCRYPTION = "ssl"
  MAIL_FROM_ADDRESS = "admin@coderstribe.net"
  MAIL_FROM_NAME = "Teacher Tribe"
  MAIL_HOST = "smtp.zoho.com"
  MAIL_MAILER = "smtp"
  MAIL_PORT = "465"
  MYSQL_ATTR_SSL_CA = "cacert.pem"
  SESSION_DRIVER = "cookie"
  SESSION_SECURE_COOKIE = "true"

[mounts]
  source = "storage_vol"
  destination = "/var/www/html/storage"
  auto_extend_size_threshold = 0

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
